### ISSUE TITLE
ImageTo3D invalid character '-' in numeric literal

### ISSUE THREAD

**Issue by okandemirel** [RageAgainstThePixel/com.rest.meshy#6] opened 2024-01-26 13:26 UTC
# Bug Report

## Overview
have ever tried ImageTo3D endpoint? I am seeing errors like this most of the time.
```
Message: 
com.utilities.rest.Runtime.RestException : <b>[POST:400]</b> <color="cyan">https://api.meshy.ai/v1/image-to-3d</color> <color="red">Failed!</color>
[Headers]
Date: Fri, 26 Jan 2024 10:59:34 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 54
Connection: keep-alive
Server: nginx
[Data] 54 bytes
[Body]
{"message":"invalid character '-' in numeric literal"}
[Errors]
HTTP/1.1 400 Bad Request
```

Most of the images inside the project needs to be uncompressed. Even making them uncompressed I do see this error.

**Comment by StephenHodgson** [comment] 2024-01-26 17:01
It was working last I checked for the last release. I'll check again.

**Comment by StephenHodgson** [comment] 2024-01-26 17:06
This is a duplicate of #3

**Comment by StephenHodgson** [comment] 2024-01-26 17:06
image to 3d using url works fine.

**Closed by StephenHodgson** 2024-01-26 17:06 UTC
Labels: bug
